apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-backend
  template:
    metadata:
      labels:
        app: rag-backend
    spec:
      containers:
      - name: api
        image: rag-backend:v2
        imagePullPolicy: Never  # Use the local image we just built
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_BASE_URL
          value: "http://host.minikube.internal:11434"  # Talk to Windows Host
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: rag-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
